# Generated by Django 5.2.6 on 2025-09-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hommes', 'Hommes'), ('femmes', 'Femmes'), ('wallets', 'Wallets'), ('packs', 'Packs')], default='hommes', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
