# Generated by Django 5.2.6 on 2025-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('coffret', 'Montre avec coffret'), ('boite_simple', 'Montre avec boîte simple'), ('wallets', 'Wallets'), ('packs', 'Packs')], default='coffret', max_length=20),
        ),
    ]
